apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: k8tlery
spec:
  containers:
  - name: k8tlery
    image: ghcr.io/xopham/k8tlery:v0.1
    imagePullPolicy: Always
    command: ["/bin/sh", "-c", "sleep infinity"]
    resources: {}
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /hostfs
      name: host
  hostNetwork: true
  hostPID: true
  tolerations:
  - key: NoExecute
    operator: Exists
  - key: NoSchedule
    operator: Exists
  - key: CriticalAddonsOnly
    operator: Exists
  volumes:
  - hostPath:
      path: /
    name: host
status: {}
