apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8tlery-admin
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8tlery-admin-sa
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8tlery-admin-crb
subjects:
- kind: ServiceAccount
  name: k8tlery-admin-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: k8tlery-admin
  apiGroup: rbac.authorization.k8s.io

