apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: k8tlery
spec:
  containers:
  - name: k8tlery
    image: ghcr.io/xopham/k8tlery:v0.1
    imagePullPolicy: Always
    command: ["/bin/sh", "-c", "sleep infinity"]
    resources: {}
  serviceAccountName: k8tlery-admin-sa
status: {}
